### ISSUE TITLE
[Feat]운동 순서 변경 시트 올릴 경우 타이머 정지 수정

### ISSUE THREAD

**Issue by 4shimi** [DeveloperAcademy-POSTECH/MacC-Team-Booster-beFLE#193]
[Feat]운동 순서 변경 시트 올릴 경우 타이머 정지 수정
이유 - onDisapear에 타이머 stop 걸려있음 (navigationLink 로 연결)

**Comment by songmoro** [comment]
타이머 stop을 on disAppear 말고 정지할 필요가 있는 뷰의 내부에서 onAppear로 호출해주는 게 좋을 듯

**Comment by 4shimi** [comment]
네 반 시트 올라와서 밖에 누르면 나가져서 한번에 처리하려고 그렇게 했는데 그게 좋을 것 같아요

**Comment by 4shimi** [comment]
타이머가 그러면 두번 돌아서 루틴 수정뷰에서 온어피어에서 시작하고 디서피어에 스탑 걸었어요
