### ISSUE TITLE
[Fix] 팁 버튼 공중부양

### ISSUE THREAD

**Issue by songmoro** [DeveloperAcademy-POSTECH/MacC-Team-Booster-beFLE#201]
<img width="507" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Booster-beFLE/assets/97587585/95a7589a-9777-47d0-b658-4b33dff66f26">

**Comment by 4shimi** [comment]
제가 해둘게요

**Comment by 4shimi** [comment]
모로 근데 이건 배경 색 지우면 괜찮아질 것 같아요
