### ISSUE TITLE
[Feat] 휴식의 경우 전체 운동일지 클릭 불가능

### ISSUE THREAD

**Issue by 4shimi** [DeveloperAcademy-POSTECH/MacC-Team-Booster-beFLE#230]
[Feat] 휴식의 경우 전체 운동일지 클릭 불가능

**Comment by songmoro** [comment]
@4shimi 이거 휴식 데이터 없는데 어떻게 확인했나요?
프리뷰에서 확인한 것 같아서 프리뷰에 네비게이션 스택 추가하고 머지했습니다.
