### ISSUE TITLE
[Feat] 운동기록 - 세트당 값이 길어질 경우 대응

### ISSUE THREAD

**Issue by samilulu** [DeveloperAcademy-POSTECH/MacC-Team-Booster-beFLE#235]
https://www.figma.com/file/sYeoBihYNDrSLnMMvNtdLf/%EB%A7%A4%ED%81%AC%EB%A1%9C---Team-Booster?type=design&node-id=4981%3A9723&mode=design&t=EcTN648CmuidreN5-1

<img width="553" alt="스크린샷 2023-11-24 오후 2 07 24" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Booster-beFLE/assets/46674678/407bb10c-392b-4a58-9704-a2a4f6902770">

**Comment by 4shimi** [comment]
네넹
